### PR TITLE
Fix routing on GitHub

### LINKED ISSUE #13: Fix routing by changing hosting
I don't think GitHub Pages can be configured to support routing beyond static sites. This causes issues with the level editor routing. Should probably move over to something else.

### PR DESCRIPTION
**Pull request by stevenhauser**
Fixes #13, supersedes #14.

- Fixes a small style issue, unrelated to this PR as a whole but I'm slapping it in there
- Adds `deploy` script which is also largely unrelated to this PR. It's been something I've been intending to add for a while. The symlinking that happens in it is relevant to this PR though.
- Adds a `symlink` script from @codingcampbell's idea in #14
- Leverages `useBasename`, also from #14 
- Adds and uses some path constants

### CODE REVIEW

**Comment by stevenhauser** [comment]
@codingcampbell check this :shit: out and let me know what you think. 

As I mentioned on #14, I really liked your idea for symlinking and how simple the initial solution was, but once all of the webpack config, file moving, path hardcoding, and relatively complex build scripts were added, I felt like either a simpler solution had to exist or it'd be easier to just use heroku or something. This is the solution I came up with which is much simpler IMO and very easy to understand.

**Comment by stevenhauser** [comment]
Oh and @codingcampbell because there's some bonus stuff in this PR, really the main things from #14 are the symlinking (`bin/symlink`) and the `createHistoryWithBasename` stuff.

**Comment by codingcampbell** [comment]
@stevenhauser I think this is a good, if narrow, approach to the issue. I was definitely targeting a more generic solution, to support more routes and use simple `<base>` routing instead of symlink soup.

Normally I caution those who avoid more flexible builds, as project scope eventually demands it, but since the game's scope is already finalized, I think throwing all the symlink and `.nojekyll` tricks into a bash script is pragmatic enough. Much better than having those things exist in the repo tree.

Another fantastic bonus with this PR is the portability of the build. I think it's great that the user wouldn't have to specify or care what subfolder (if any) the static build will exist. :+1: :shipit:

**Comment by stevenhauser** [comment]
Yeah I looked into `base` but wasn't having a ton of luck with it with the router—maybe I set it up wrong. And like you said, the project's scope is more or less final, so I definitely wanted as simple of a solution as possible, even if it meant giving up flexibility in some areas (more routes) while providing more flexibility in others (no hardcoded subdirectories).

**Pull request merged**
